name: flutter_flavors
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.3
  get: ^4.7.2
  floor: ^1.5.0
  flutter_screenutil: ^5.9.3
  double_back_to_close_app: ^2.1.0
  intl: ^0.20.2
  table_calendar: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.0.0
  floor_generator: any


flutter:
  uses-material-design: true

  # Assets section
  assets:
    - assets/icons/
    - assets/images/
